version: "3.7"

services:
  php:
    build:
      args:
        user: alex
        uid: 1000
      context: ./docker
      dockerfile: php-fpm.Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php


